# Use official Python image
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy dependencies and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code
COPY . .

# Expose FastAPI port
EXPOSE 5000

# Run the Python service
CMD ["uvicorn", "microservice:app", "--host", "0.0.0.0", "--port", "5000"]
